SH1ProjeUygulamasi.WebAPIUsing/Areas/Admin/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;

namespace SH1ProjeUygulamasi.WebAPIUsing.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class MainController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

SH1ProjeUygulamasi.WebAPIUsing/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SH1ProjeUygulamasi.Core.Entities;

namespace SH1ProjeUygulamasi.WebAPIUsing.Areas.Admin.Controllers
{
	[Area("Admin")] //verilmezse sayfa bulunamıyor hatası alınır
	public class UsersController : Controller
	{
		private readonly HttpClient _httpClient; //dependences injection ile yapıldı (inversion için)
		static string _apiAdres = "http://localhost:5063/Api/Users";

		public UsersController(HttpClient httpClient)
		{
			_httpClient = httpClient;
		}

		// GET: UsersController
		public async Task<ActionResult> Index()
		{
			var model = await _httpClient.GetFromJsonAsync<List<User>>(_apiAdres); //istek atıldığında json gelicek, gelen json list of category e çevirecek
			return View(model);
		}

		// GET: UsersController/Details/5
		public async Task<ActionResult> DetailsAsync(int id)
		{
			var model = await _httpClient.GetFromJsonAsync<Slider>($"{_apiAdres}/{id}");
			return View(model);
		}

		// GET: UsersController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: UsersController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CreateAsync(User collection)
		{
			if (ModelState.IsValid)
			{
				try
				{
					var response = await _httpClient.PostAsJsonAsync(_apiAdres, collection);
					if (response.IsSuccessStatusCode)
					{
						return RedirectToAction(nameof(Index));
					}
					ModelState.AddModelError("", "Kayıt Yapılamadı!");
				}
				catch
				{
					ModelState.AddModelError("", "Hata Oluştu!");
				}
			}
			return View(collection);
		}

		// GET: UsersController/Edit/5
		public async Task<ActionResult> EditAsync(int id)
		{
			var model = await _httpClient.GetFromJsonAsync<Category>($"{_apiAdres}/{id}");
			return View(model);
		}

		// POST: UsersController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> EditAsync(int id, User collection)
		{
			if (ModelState.IsValid)
			{
				try
				{
					var response = await _httpClient.PutAsJsonAsync(_apiAdres + "/" + id, collection);
					if (response.IsSuccessStatusCode)
					{
						return RedirectToAction(nameof(Index));
					}
					ModelState.AddModelError("", "Kayıt Yapılamadı!");
				}
				catch
				{
					ModelState.AddModelError("", "Hata Oluştu!");
				}
			}
			return View(collection);
		}

		// GET: UsersController/Delete/5
		public async Task<ActionResult> DeleteAsync(int id)
		{
			var model = await _httpClient.GetFromJsonAsync<Category>($"{_apiAdres}/{id}");
			return View(model);
		}

		// POST: UsersController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteAsync(int id, User collection)
		{
			try
			{
				var response = await _httpClient.DeleteAsync(_apiAdres);
				if (response.IsSuccessStatusCode)
				{
					return RedirectToAction(nameof(Index));
				}
				ModelState.AddModelError("", "İşlem Başarısız!");
			}
			catch
			{
				ModelState.AddModelError("", "Hata Oluştu!");
			}
			return View(collection);
		}
	}
}

SH1ProjeUygulamasi.WebAPIUsing/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using SH1ProjeUygulamasi.Core.Entities;

namespace SH1ProjeUygulamasi.WebAPIUsing.Controllers
{
	public class CategoriesController : Controller
	{
		private readonly HttpClient _httpClient;

		public CategoriesController(HttpClient httpClient)
		{
			_httpClient = httpClient;
		}
		static string _apiAdres = "http://localhost:5063/Api/";

		public async Task<IActionResult> IndexAsync(int? id)
		{
			if (id == null) //eğer adres çubuğundan id gelmezse
			{
				return BadRequest(); //feriye geçersiz istek hatası dön.
			}

			var model = await _httpClient.GetFromJsonAsync<List<Category>>($"{_apiAdres}Categories/{id}"); //istek atıldığında json gelicek, gelen json list of category e çevirecek
			if (model == null)
			{
				return NotFound();
			}
			var products = await _httpClient.GetFromJsonAsync<List<Product>>($"{_apiAdres}Products/GetProductsPageCategoryId/{id}");
			//if (products is not null)
			//{
			//	model.Products = products;
			//}
			return View(model);
		}
	}
}

SH1ProjeUygulamasi.WebAPIUsing/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using SH1ProjeUygulamasi.Core.Entities;

namespace SH1ProjeUygulamasi.WebAPIUsing.Controllers
{
	public class ProductsController : Controller
	{
		private readonly HttpClient _httpClient;

		public ProductsController(HttpClient httpClient)
		{
			_httpClient = httpClient;
		}
		static string _apiAdres = "http://localhost:5063/Api/Products";

		public async Task<IActionResult> IndexAsync(string q = "")
		{
			var products = await _httpClient.GetFromJsonAsync<List<Product>>($"{_apiAdres}Products/GetProductsBySearch/{q}");
			return View(products);
		}

		public async Task<IActionResult> DetailAsync(int? id)
		{
			//var model = _context.Products.FirstOrDefault(p => p.IsActive && p.Id == id);
			if (id is null)
			{
				return BadRequest("Geçersiz İstek!");
			}
			var products = await _httpClient.GetFromJsonAsync<Product>($"{_apiAdres}Products/{id}");
			//if (model == null)
			//{
			//	return NotFound("Ürün Bulunamadı!");
			//}
			var productImages = await _httpClient.GetFromJsonAsync<List<ProductImage>>($"{_apiAdres}ProductImages/GetProductImagesByProductId/{id}");
			//model.ProductImages = productImages;
			return View();
		}

		public IActionResult FetchCrud()
		{
			return View();
		}
	}
}

SH1ProjeUygulamasi.WebAPIUsing/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SH1ProjeUygulamasi.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Admin" asp-controller="Main" asp-action="Index">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Slider Yönetimi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categories" asp-action="Index">Kategori Yönetimi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Ürün Yönetimi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Create">Kullanıcı Yönetimi</a>
                        </li>
                    </ul>
                </div>
                <a class="btn-outline-info me-2" href="/" asp-action="Index" target="_blank">Siteyi Görüntüle</a>
                <a class="btn btn-danger" asp-area="" asp-controller="Account" asp-action="LogOut">Oturumu Kapat</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @Html.Raw(TempData["Message"])
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SH1ProjeUygulamasi.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>